/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AmiciRouteImport } from './routes/amici'
import { Route as GiocaRouteImport } from './routes/gioca'
import { Route as PartiteRouteImport } from './routes/partite'
import { Route as ProfiloRouteImport } from './routes/profilo'
import { Route as RegoleRouteImport } from './routes/regole'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AmiciRoute = AmiciRouteImport.update({
  id: '/amici',
  path: '/amici',
  getParentRoute: () => rootRouteImport,
} as any)
const GiocaRoute = GiocaRouteImport.update({
  id: '/gioca',
  path: '/gioca',
  getParentRoute: () => rootRouteImport,
} as any)
const PartiteRoute = PartiteRouteImport.update({
  id: '/partite',
  path: '/partite',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfiloRoute = ProfiloRouteImport.update({
  id: '/profilo',
  path: '/profilo',
  getParentRoute: () => rootRouteImport,
} as any)
const RegoleRoute = RegoleRouteImport.update({
  id: '/regole',
  path: '/regole',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/amici': typeof AmiciRoute
  '/gioca': typeof GiocaRoute
  '/partite': typeof PartiteRoute
  '/profilo': typeof ProfiloRoute
  '/regole': typeof RegoleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/amici': typeof AmiciRoute
  '/gioca': typeof GiocaRoute
  '/partite': typeof PartiteRoute
  '/profilo': typeof ProfiloRoute
  '/regole': typeof RegoleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/amici': typeof AmiciRoute
  '/gioca': typeof GiocaRoute
  '/partite': typeof PartiteRoute
  '/profilo': typeof ProfiloRoute
  '/regole': typeof RegoleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/amici' | '/gioca' | '/partite' | '/profilo' | '/regole'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/amici' | '/gioca' | '/partite' | '/profilo' | '/regole'
  id:
    '__root__' | '/' | '/amici' | '/gioca' | '/partite' | '/profilo' | '/regole'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AmiciRoute: typeof AmiciRoute
  GiocaRoute: typeof GiocaRoute
  PartiteRoute: typeof PartiteRoute
  ProfiloRoute: typeof ProfiloRoute
  RegoleRoute: typeof RegoleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/amici': {
      id: '/amici'
      path: '/amici'
      fullPath: '/amici'
      preLoaderRoute: typeof AmiciRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gioca': {
      id: '/gioca'
      path: '/gioca'
      fullPath: '/gioca'
      preLoaderRoute: typeof GiocaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partite': {
      id: '/partite'
      path: '/partite'
      fullPath: '/partite'
      preLoaderRoute: typeof PartiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profilo': {
      id: '/profilo'
      path: '/profilo'
      fullPath: '/profilo'
      preLoaderRoute: typeof ProfiloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regole': {
      id: '/regole'
      path: '/regole'
      fullPath: '/regole'
      preLoaderRoute: typeof RegoleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AmiciRoute: AmiciRoute,
  GiocaRoute: GiocaRoute,
  PartiteRoute: PartiteRoute,
  ProfiloRoute: ProfiloRoute,
  RegoleRoute: RegoleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
